# backend/data/builder.py
"""
Builds a query-centric training dataset for the ranking model.

This script transforms raw user-item interaction data (ratings) into a
structured dataset for a learning-to-rank task. The goal is to create a dataset
where each row represents a (query, candidate, label) tuple.

Methodology:
1. Load user ratings.
2. For each user, simulate a "query" by using a subset of their highly-rated movies.
3. The "ground truth" (positive labels) are other movies the same user rated highly.
4. Negative labels are generated by sampling movies the user has not interacted with.
"""

import logging
import os

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
log = logging.getLogger(__name__)


def build_ranking_dataset(
    ratings_path: str,
    output_path: str,
    min_rating: float = 4.0,
    min_history_size: int = 10,
    max_users: int = None,
    query_size: int = 5,
    num_neg_samples: int = 2,
    chunk_size: int = 20000,
) -> None:
    """
    Main function to generate and save the query-centric ranking dataset.
    This version is optimized to process data in chunks to manage memory usage.
    """
    log.info(f"Starting dataset building process.")
    log.info(f"Loading ratings from {ratings_path}...")
    ratings = pd.read_parquet(
        ratings_path, columns=["userId", "movieId", "rating", "timestamp"]
    )
    log.info(f"Loaded {len(ratings)} raw ratings records.")

    # 1. Filter for relevant interactions and users
    log.info(
        f"Filtering for positive interactions (rating >= {min_rating}) and active users (history >= {min_history_size} items)..."
    )
    positive_interactions = ratings[ratings["rating"] >= min_rating].copy()

    user_counts = positive_interactions["userId"].value_counts()
    valid_users = user_counts[user_counts >= min_history_size].index

    if max_users and max_users < len(valid_users):
        log.info(f"Subsampling to {max_users} users...")
        valid_users = np.random.choice(valid_users, max_users, replace=False)

    # --- Process in Chunks ---
    user_chunks = np.array_split(valid_users, max(1, len(valid_users) // chunk_size))
    log.info(
        f"Splitting {len(valid_users)} users into {len(user_chunks)} chunks of ~{chunk_size} for processing."
    )

    all_movie_ids = ratings["movieId"].unique()
    global_positive_movie_ids = set(positive_interactions["movieId"])
    negative_pool = np.array(list(set(all_movie_ids) - global_positive_movie_ids))
    log.info(
        f"Global negative candidate pool size: {len(negative_pool)} unique movie IDs."
    )

    total_examples = 0
    writer = None
    for i, user_chunk in enumerate(user_chunks):
        log.info(
            f"--- Processing Chunk {i + 1}/{len(user_chunks)} ({len(user_chunk)} users) ---"
        )

        chunk_interactions = positive_interactions[
            positive_interactions["userId"].isin(user_chunk)
        ]

        # 2. Vectorized creation of positive examples for the chunk
        df = chunk_interactions.sort_values(["userId", "timestamp"])

        query_cols = []
        for j in range(1, query_size + 1):
            col_name = f"query_movie_id_{j}"
            df[col_name] = df.groupby("userId")["movieId"].shift(j)
            query_cols.append(col_name)

        df.dropna(subset=query_cols, inplace=True)
        if df.empty:
            log.warning(f"No valid query windows in chunk {i + 1}, skipping.")
            continue

        df[query_cols] = df[query_cols].astype(int)
        df["query_movie_ids"] = df[query_cols[::-1]].values.tolist()

        df_positive = df[["query_movie_ids", "movieId"] + query_cols].rename(
            columns={"movieId": "candidate_movie_id"}
        )
        df_positive["label"] = 1
        log.info(f"Chunk {i + 1}: Generated {len(df_positive)} positive examples.")

        if df_positive.empty:
            log.warning(
                f"No positive examples in chunk {i + 1}, skipping negative sampling."
            )
            continue

        # 3. Vectorized generation of negative examples for the chunk
        df_negative = df_positive.loc[df_positive.index.repeat(num_neg_samples)].copy()

        if len(negative_pool) > 0:
            random_candidates = np.random.choice(
                negative_pool, len(df_negative), replace=True
            )
            df_negative["candidate_movie_id"] = random_candidates
            df_negative["label"] = 0

            colliding_mask = pd.Series(False, index=df_negative.index)
            for col in query_cols:
                colliding_mask |= df_negative[col] == df_negative["candidate_movie_id"]

            colliding_indices = df_negative[colliding_mask].index
            if not colliding_indices.empty:
                df_negative.drop(colliding_indices, inplace=True)
        else:
            log.warning(
                "Negative pool is empty, generating no negative samples for this chunk."
            )
            df_negative = df_negative.iloc[0:0]

        log.info(f"Chunk {i + 1}: Generated {len(df_negative)} negative examples.")

        # 4. Combine and save the chunk's dataset using ParquetWriter
        df_positive.drop(columns=query_cols, inplace=True)
        df_negative.drop(columns=query_cols, inplace=True)

        df_chunk_final = pd.concat([df_positive, df_negative], ignore_index=True)

        if df_chunk_final.empty:
            log.warning(
                f"Chunk {i + 1} resulted in an empty dataset. Nothing to write."
            )
            continue

        df_chunk_final = df_chunk_final.sample(frac=1).reset_index(drop=True)

        log.info(
            f"Writing {len(df_chunk_final)} examples from chunk {i + 1} to Parquet file..."
        )
        table = pa.Table.from_pandas(df_chunk_final, preserve_index=False)

        if writer is None:
            writer = pq.ParquetWriter(output_path, table.schema)

        writer.write_table(table)
        total_examples += len(df_chunk_final)

    if writer:
        writer.close()
        log.info("Parquet writer closed.")

    log.info(f"All chunks processed. Total examples in final dataset: {total_examples}")
    log.info(f"Dataset successfully saved to {output_path}.")
    log.info("✨ Dataset building process completed successfully! ✨")
