# backend/training/ranking/native/ranker.conf

# Task
task = train
boosting_type = gbdt
objective = lambdarank
metric = ndcg
label_column = 0

# Data
data = rank.train
valid = rank.test
label_column = 0
group_column = "" # Queries are in separate .query files
# Input files
# train_data_file = rank.train
# train_query_file = rank.train.query
# valid_data_file = rank.test
# valid_query_file = rank.test.query

# Hyperparameters
num_iterations = 500
learning_rate = 0.05
num_leaves = 31
feature_fraction = 0.8
bagging_fraction = 0.8
bagging_freq = 5
min_data_in_leaf = 20

# Efficiency
two_pass = true
max_bin = 255

# Output
output_model = lgbm_lambdarank.txt
